# Generated by Django 4.2.6 on 2023-11-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coches', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioVenta', models.CharField(max_length=100)),
                ('metodoPago', models.CharField(max_length=100)),
                ('fechaVenta', models.DateField(max_length=100)),
                ('telefonoCliente', models.CharField(max_length=12)),
                ('direccionCliente', models.CharField(max_length=100)),
                ('correoCliente', models.EmailField(max_length=100)),
                ('ciudadCliente', models.CharField(max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='cliente_id')),
                ('coches_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coches.coches', verbose_name='coches_id')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
    ]
