# Generated by Django 4.2.6 on 2023-11-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cCliente', models.CharField(max_length=100)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('telefonoCliente', models.CharField(max_length=12)),
                ('direccionCliente', models.CharField(max_length=100)),
                ('correoCliente', models.EmailField(max_length=100)),
                ('ciudadCliente', models.CharField(max_length=100)),
                ('passwordCliente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
